spring:
  application:
    name: firstAPI
  data:
    mongodb:
      host: localhost
      port: 27017
      database: journalDb
  mail:
    host: smtp.gmail.com
    port: 587
    username: tg21014@gmail.com
    password: upbr cmvu menl rbay
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
